# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='post',
            field=models.ManyToManyField(to='postings.BlogPost'),
        ),
    ]
