# Generated by Django 2.0.2 on 2018-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_seed_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='post',
            field=models.ManyToManyField(blank=True, to='postings.BlogPost'),
        ),
    ]
