# Generated by Django 2.0.2 on 2018-07-28 02:01

from django.db import migrations, models
import django.db.models.fields
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0003_auto_20180723_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='location',
            field=jsonfield.fields.JSONField(default=None, verbose_name={'lat': models.CharField(), 'lon': django.db.models.fields.CharField}),
            preserve_default=False,
        ),
    ]
