# Generated by Django 2.0.2 on 2018-07-28 02:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0004_seed_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='location',
            field=jsonfield.fields.JSONField(),
        ),
    ]
