# Generated by Django 2.0.2 on 2018-07-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0005_auto_20180728_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='location',
        ),
    ]
