# Generated by Django 2.0.2 on 2018-07-28 15:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0007_seed_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='gps_lat',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='gps_lon',
        ),
        migrations.AlterField(
            model_name='seed',
            name='location',
            field=jsonfield.fields.JSONField(blank='', default={'latitude': models.DecimalField(decimal_places=6, max_digits=9), 'longitude': models.DecimalField(decimal_places=6, max_digits=9)}),
        ),
    ]
