# Generated by Django 2.0.2 on 2018-07-28 16:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0009_auto_20180728_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='location',
            field=jsonfield.fields.JSONField(default='{"latitude": "", "longitude": ""}'),
        ),
    ]
