# Generated by Django 2.0.2 on 2018-07-28 16:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0010_auto_20180728_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='location',
            field=jsonfield.fields.JSONField(),
        ),
    ]
