# Generated by Django 2.0.2 on 2018-07-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0011_auto_20180728_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='picture',
            field=models.ImageField(default=None, upload_to='pics'),
            preserve_default=False,
        ),
    ]
