# Generated by Django 2.0.2 on 2018-07-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0013_auto_20180731_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
